//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LYSApp.Data.DBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bed
    {
        public int BedID { get; set; }
        public int RoomID { get; set; }
        public long UserID { get; set; }
        public bool Status { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> LastUpdatedOn { get; set; }
        public Nullable<int> BedStatus { get; set; }
        public Nullable<System.DateTime> StatusUpdateDate { get; set; }
    
        public virtual Room Room { get; set; }
        public virtual User User { get; set; }
    }
}
