//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LYSApp.Data.DBEntity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class LYSAdminEntities : DbContext
    {
        public LYSAdminEntities()
            : base("name=LYSAdminEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<Apartment> Apartments { get; set; }
        public virtual DbSet<Area> Areas { get; set; }
        public virtual DbSet<Bed> Beds { get; set; }
        public virtual DbSet<Block> Blocks { get; set; }
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<HouseAmenity> HouseAmenities { get; set; }
        public virtual DbSet<HouseImage> HouseImages { get; set; }
        public virtual DbSet<HouseReview> HouseReviews { get; set; }
        public virtual DbSet<House> Houses { get; set; }
        public virtual DbSet<PGDetail> PGDetails { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Room> Rooms { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<UserClaim> UserClaims { get; set; }
        public virtual DbSet<UserDetail> UserDetails { get; set; }
        public virtual DbSet<UserLogin> UserLogins { get; set; }
        public virtual DbSet<User> Users { get; set; }
    
        public virtual ObjectResult<GetHouseListByPGDetailsID_Result> GetHouseListByPGDetailsID(Nullable<int> pgDetailsId)
        {
            var pgDetailsIdParameter = pgDetailsId.HasValue ?
                new ObjectParameter("pgDetailsId", pgDetailsId) :
                new ObjectParameter("pgDetailsId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetHouseListByPGDetailsID_Result>("GetHouseListByPGDetailsID", pgDetailsIdParameter);
        }
    }
}
