//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LYSApp.Data.DBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PGReview
    {
        public PGReview()
        {
            this.PGDetails = new HashSet<PGDetail>();
        }
    
        public int PGReviewID { get; set; }
        public long UserID { get; set; }
        public int HouseID { get; set; }
        public string Comments { get; set; }
        public Nullable<decimal> Rating { get; set; }
        public Nullable<System.DateTime> CommentTime { get; set; }
    
        public virtual House House { get; set; }
        public virtual ICollection<PGDetail> PGDetails { get; set; }
        public virtual User User { get; set; }
    }
}
